### ISSUE TITLE
Stage seems to stop sending/receiving events after a certain point.

### ISSUE THREAD

**Issue by gloriajw** [upstage-org/mobilise#133]
Restarting MQTT on the server, and then reloading the stage, sometimes helps. But it happens consistently. it seems like either Vue is occupying too much memory and can't function after a certain point, or its connections and state are somehow growing stale and stop working. 

I think this will be easier to nail down once there's real communication with the back end. We will know the number of bytes sent, and when, assets loaded, etc.

**Comment by vickis** [comment]
Great it was a bombardment of messages and action from the young girls
there
And definitely multiple repeated commands in attempts to do things on stage
A good test as was not super crowded with players ;)

**Comment by gloriajw** [comment]
We discussed this, and discovered that Phat is sending the entire image when it is manipulated. When we have Vue hitting the real back end, everything will be associated with IDs. Instructions will be sent for objects on the stage similar to this: "ID 5 rotate 90 degrees". 
In the interim, Phat is going to send less data, generate temporary IDs for now for objects, and come up with his own reduction to ID and instruction to each browser session. 
We do still need to handle load, it will happen again even after this optimization. Maybe caching events in the browser would help?

**Comment by nguyenhongphat0** [comment]
Thank you for helping me explains them so clearly, Gloria 🤗 I can now confirm they are the real problem, because I did a test with a big drawing (full screen drawing) and a small drawing. Moving/rorating/delete the big drawing took a delay of 1-2 seconds but at the same time it took immediately with the small drawing. Fun fact: a message with base64 inside can be 1000 times as large as a normal message

I'll fix this issue for now by sending only the ID on manipulating. But this has one drawback: if someone enter the stage in the middle of the performance, they won't see that drawing. Because I only send the base64 once and only once it is placed on the stage, so only the audiences who witness the drawing placed on the stage can only see it moving/scaling/rotating/etc... But this can be fixed also with some help from backend side later 🌻

**Comment by nguyenhongphat0** [comment]
https://user-images.githubusercontent.com/29925961/107017040-3c27d000-67d1-11eb-979c-f0020d5bc169.mp4

**Comment by helenvarley** [comment]
the video is a great demo - i can see the software "thinking", in the time of sending the messages :)
great that you found a solution - & also are working on the drawback of those entering the stage late not seeing the drawing. good thinking!! :)

**Comment by gloriajw** [comment]
I think this has been resolved, closing.
