### ISSUE TITLE
assign media to stage during upload

### ISSUE THREAD

**Issue by vickis** [upstage-org/mobilise#17]
as a user when i upload media in the same interface i can also set which stage this media appears on (this can be multiple stages

**Comment by helenvarley** [comment]
this is high priority! at the moment it is quite a lengthy process to assign media to a stage. it's confusing, once you have uploaded it, to have to then go to the stage edit interface and find the media item in order to be able to assign it to the stage. 
in the media upload interface, there should be a list of all available stages (that you have permission to edit) and the possibility to select one or more stages to which the media item should be assigned.

**Comment by vickis** [comment]
Agree important :)

**Comment by helenvarley** [comment]
here's how it worked in the old UpStage: in the media upload interface, you could select any number of stages for the media item to be immediately assigned to:
![audio_upload](https://user-images.githubusercontent.com/3437324/116415082-5e157980-a839-11eb-8e4c-4d300c1ae96f.PNG)

**Comment by helenvarley** [comment]
cool - there are quite a few issues related to the upload process ... i hope you can find them all! (dropdown menu for media type, multiframe option, replace ...) #279, #208, #17 ... maybe some others .... :laughing:

**Comment by nguyenhongphat0** [comment]
I believe this issue is resolved 😎
