### ISSUE TITLE
drawing causes browser to become unresponsive

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#192]
when i try to draw on the stage, i get the message "A web page is slowing down your browser. What would you like to do?" and the options Stop it or Wait. (firefox on linux)
also my computer fan goes crazy.
& i can do nothing, until i tell the browser to stop it or reload the page.

**Comment by nguyenhongphat0** [comment]
Seems like the Drawing tool is using too much resource. I'll look for a way to increase it's performance. Can you provide me more information about your machine, Helen. How many RAM memory do you have, etc,...

**Comment by helenvarley** [comment]
Ubuntu
Release 20.04.2 LTS (Focal Fossa) 64-bit
Kernel Linux 5.4.0-67-generic x86_64
MATE 1.24.0

Hardware
Memory: 7,6 GiB
Processor: Intel® Core™ i5-7200U CPU @ 2.50GHz × 4 
Graphics: Mesa Intel® HD Graphics 620 (KBL GT2)

Available disk space: 606,6 GB

and i'm using Firefox 86.0 (64-bit)

**Comment by nguyenhongphat0** [comment]
That's a strong hardware environment, thank you @helenvarley 
This issue is hard to resolve, pls give me time working on this

**Comment by nguyenhongphat0** [comment]
Hi @helenvarley , I found a memory leaks inside the Undo feature, and found a way to optimise it. I rolled it on app1, remember to make a fresh reload (Ctrl+F5) the next time you visit the stage

I hope the optimise worked (technically it should works 🤣), because I'm implementing the live action, and it will use even more resource than this 🚀

**Comment by helenvarley** [comment]
seems to be working much better now! :+1:
