### ISSUE TITLE
email free user 

### ISSUE THREAD

**Issue by vickis** [upstage-org/mobilise#2]
as an admin i want to be able to add a user for a one-0ff session (as in a guest user) - override the requirement for an email 
all others must supply an email to register an account

**Comment by helenvarley** [comment]
more specifically, i want to be able to batch add and batch edit guest users for workshops.
the guest user should be able to have player access to specified stages, but not be able to upload or edit media. 
the guest user account does not have an email address associated with it.
ideally it should be possible to manage and batch edit the guest users from within the admin interface.

**Comment by nguyenhongphat0** [comment]
Hi @helenvarley , if you want to priotise an issue, please put it on top of the TODO list here: https://github.com/upstage-org/mobilise/projects/1 rather than nail it with the `prioritize` label. Let me do this one for you 🙌 
I know that I was the person created the `prioritise` label, sorry 😅 The todo list is just more convince!
