### ISSUE TITLE
wrong date for media upload

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#207]
it's still showing the wrong date for the media upload - i have just uploaded a prop & an avatar, but it says that they were uploaded "a day ago" ...
![Screenshot at 2021-03-30 15-08-44](https://user-images.githubusercontent.com/3437324/112994052-22b85a00-916a-11eb-999e-8686b53b69a1.png)

**Comment by nguyenhongphat0** [comment]
Hi @gloriajw, @paul-rohrlach, it's look like this Python code: `datetime.utcnow()` return the moment I restarted upstage service, instead of the current moment 🤔 

I'm quite sure about this because the `9 days ago issue` resolved itself after I ran the command `systemctl restart upstage.service`. And the last time I ran that command was about 9 days before that

<img width="995" alt="Screenshot 2021-03-30 at 22 53 49" src="https://user-images.githubusercontent.com/29925961/113019137-7a2aea00-91ab-11eb-8f29-05a9a40d5dda.png">
(Vue and Cute Dog was uploaded at the same time, but Cute Dog was uploaded before restarting, and Vue was after)

**Comment by paul-rohrlach** [comment]
@nguyenhongphat0 can you confirm that the UI is indeed receiving the incorrect date from the server?

**Comment by nguyenhongphat0** [comment]
Yes, Paul! After upload the avatar the server return 31/3/3021
<img width="1405" alt="Screenshot 2021-04-01 at 12 13 02" src="https://user-images.githubusercontent.com/29925961/113246663-aea1c180-92e3-11eb-837b-44a570461a47.png">


But on the app1 the time was correctly as 1/4/2021
<img width="227" alt="Screenshot 2021-04-01 at 12 11 09" src="https://user-images.githubusercontent.com/29925961/113246522-5b2f7380-92e3-11eb-9fdd-677b1755b289.png">

**Comment by paul-rohrlach** [comment]
Okay, I'll take a look

**Comment by nguyenhongphat0** [comment]
Hi Paul, I found this on the internet: https://www.odoo.com/forum/help-1/fields-datetime-now-show-the-time-of-the-latest-restart-not-the-current-time-107582. It's look very similar to our situation, can you verify that it is the right fix 🤔 If it is, I'll follow it to solve this issue 👌

**Comment by paul-rohrlach** [comment]
It should be simple enough to run the server code on your development machine, feel free to give it a go.  If it works, submit a PR

**Comment by nguyenhongphat0** [comment]
Okay @paul-rohrlach , I'll give it a try. Thank you 🙏
