### ISSUE TITLE
Text tool improvment

### ISSUE THREAD

**Issue by elisadcg** [upstage-org/mobilise#220]
The actual list of Font available in Stage are proprietary font. I suggest to choose free font and more efficient for screen.
There is 20 fonts, i suggest this 20 others fonts : 
Roboto, Open Sans, Lato, Roboto Condensed, Oswald, Poppins, Roboto mono, PT Sans, Ubuntu, Playfair Display, Pt serif, Fira sans, Bebas neue, Anton, Lobster, Varela Round, Arvo, Pacifico, Asap, Overpass; Abril Fatface.

For bublle : i suggest more padding between the bubble and the text. It would be wonderful if you can let it on stage while we read it 4 times.

And please the text on the bubble have to be display with an line-height:140-160%.

**Comment by helenvarley** [comment]
good idea to use free fonts, in keeping with the software being open source! :+1:

**Comment by helenvarley** [comment]
it's very difficult to move a text box once you have it on stage. once you have clicked within the text and get the cursor to edit it, it's no longer possible to move it by drag and drop, unless you click the lightbulb on and off. is this deliberate, or necessary somehow? i guess we can learn it, but it is an extra thing to remember and sometimes we want to move it quickly.

**Comment by helenvarley** [comment]
is something wrong with the text tool? i'm not able to save anything at the moment. hitting save just gives me the bar with the new icon on it.

**Comment by vickis** [comment]
Yep - noted that the other night

**Comment by elisadcg** [comment]
Is it possible to put only free font available on text tool ? What do artist think about this idea ?

**Comment by vickis** [comment]
Agree :)

**Comment by helenvarley** [comment]
sounds good to me :)

**Comment by nguyenhongphat0** [comment]
Thank you for the great font collections, @elisadcg! I added them to the available font selection list 👍 

<img width="911" alt="Screenshot 2021-07-18 at 15 50 13" src="https://user-images.githubusercontent.com/29925961/126061433-be843cb4-5cd9-4ea0-b279-c06410c9f057.png">

Remember: these font are not built-in fonts (they're not installed as part of operating system), so we have to load these font from a CDN (I'm using google font api). This means an increase in page loading time when someone first visit UpStage. But we don't have to worry about it at the moment since 20 fonts is not too much 😅

**Comment by vickis** [comment]
that looks great Phat! :)
