### ISSUE TITLE
Dashboard table managment

### ISSUE THREAD

**Issue by elisadcg** [upstage-org/mobilise#233]
Actually the name of the stage is direct link to the stage. I think if it's not explained for the user is could be surprising. I recommand to add a clear button Enter Stage. I recommend to change Edit Stage into Manage Stage. And why not to put direct icon-link to duplicate stage, delete stage, enter stage, see the recorded video etc. 
![dashboard-table](https://user-images.githubusercontent.com/7611913/113835268-1d6f9680-978c-11eb-9bdf-2b4a5d9b785a.png)

**Comment by helenvarley** [comment]
great! i would suggest that the recorded link could be on the "detail" screen, as we also need a link for accessing just the chat, and maybe other statistics e.g. the number of audience that were there at the performance time (i know, another feature ;) ) - there are quite a lot of things that might (in the future) be good to have access to, so rather than have too many things in the list of stages, there can be all of this kind of information in the "detail" interface, that is things that are more information about the stage. then the actually editing, making changes etc can come under "manage stage". 
the buttons for duplicating & deleting would be great to have on the dashboard list of stages.

**Comment by elisadcg** [comment]
Ok i make a wireframe to record it. It would be precious to get the details of statistique, what do chat link, and if you prefer Manage Stage or Edit Stage
![dashboard-table2](https://user-images.githubusercontent.com/7611913/113862263-78af8200-97a8-11eb-82f8-5ce615e43b7b.png)

**Comment by helenvarley** [comment]
i think "Manage Stage" is probably best, as within that we have "edit stage" which is about the settings (layout etc), media, etc & then other "manage" things for example making the stage publily visible or not, & which players have access - things that are not editing the stage itself, but managing the access.

for the details: this is where we find information about the stage; so the name and description, and access to recordings and statistics. we need to work this one out more, because there could be (usually WILL be) multpile performances on the same stage, so we would want to see the statistics & recordings for each one separately. 
#59 is for real time statistics - maybe we need another issue for documentation & historical statistics?
#53 is the recording feature

**Comment by paul-rohrlach** [comment]
Adding to R2-201 backlog.

**Comment by elisadcg** [comment]
![233-stagemanagement02](https://user-images.githubusercontent.com/7611913/114670738-9f6b3c80-9d03-11eb-8172-4455c66a8930.png)

**Comment by nguyenhongphat0** [comment]
And the numbers of players, will we show it on the table as well? Or we will show it inside Stage Information popup? 🤔

**Comment by elisadcg** [comment]
helen said that, like in theater, any stage could be show several times. So it's probably better to get for each live their own statistique

**Comment by vickis** [comment]
Numbers can just show in stage (it is the live information that is
important - especially audience :)

It might be useful for a maximum number to be recorded (for shows )
But it should  be possible to see these  in the recording
