### ISSUE TITLE
Creating new Stage : chat button

### ISSUE THREAD

**Issue by elisadcg** [upstage-org/mobilise#241]
When we creat a new Stage, the Clear Chat button is not usefull because none use it already. Can we hide it at this step ?
![Screenshot_20210408_101317](https://user-images.githubusercontent.com/7611913/113991144-79045780-9852-11eb-86f9-7e9bef06acf3.png)

**Comment by elisadcg** [comment]
And when i creat this new Stage, i have choose the Live Stage status option. And when i come back, the Status is not identified. We don't know it the stage is in Live, or Upcoming or Rehearsal status ? Is it possible/useful to get visible wich status is actually the Stage ?

**Comment by helenvarley** [comment]
agree, both "clear chat" and "sweep stage" are not needed at this point. also "delete stage" can go, as you don't need to delete it if you haven't created it yet!

there might be other things that could be useful on this screen, but of course once you create the stage you arrive at the manage/edit interface, don't you? so then you can do all the other things you want to set. this is just to get the name of the stage.

maybe we don't even need to choose live/upcoming/rehearsal at this point either - the default should be rehearsal; because at this point of creation, the stage is blank, empty, so why make it live or upcoming? i think it's best to make the default state of a new stage be "rehearsal" (only visible & accessible to the owner) and then to be set in the manage stage interface.

**Comment by nguyenhongphat0** [comment]
This issue is resolved as well 👌 

<img width="1331" alt="Screenshot 2021-06-12 at 14 57 23" src="https://user-images.githubusercontent.com/29925961/121769567-814c7c00-cb8e-11eb-8165-a99f1cdf595e.png">
