### ISSUE TITLE
on stage media object frame should aways fit to the object

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#275]
i have noticed that sometimes when resizing an object on the stage (avatar, prop, video, drawing, text) it's very easy to end up with a frame that is larger than the actual object - extending above and below. this creates problems when it overlaps other media, and can prevent you from being able to select the media that you need to. 
can it be that the frame is always the same dimensions as the object? 

example in this image: dave's frame makes it impossible to select the flowergirl avatar.
![Screenshot at 2021-04-18 22-04-33](https://user-images.githubusercontent.com/3437324/115159181-274d9f80-a092-11eb-80da-b7a3fbc6412c.png)

**Comment by helenvarley** [comment]
i guess this is connected to #211 - if the scaling handles worked as expected, it would not create empty frame space above and below the image, would it?

**Comment by nguyenhongphat0** [comment]
It is because you upload a 1:1 ratio avatar, but you scale it to a different ratio (for example 1:4), so it has to have space to keep the avatar look good. If you don't want space, the avatar must be skew or crop like this:

<img width="160" alt="Screenshot 2021-04-19 at 12 31 42" src="https://user-images.githubusercontent.com/29925961/115186054-34f33b80-a10b-11eb-913b-4f2ffa889dc6.png" style="display: inline"> <img width="160" alt="Screenshot 2021-04-19 at 12 32 03" src="https://user-images.githubusercontent.com/29925961/115186078-40defd80-a10b-11eb-8311-130d33ef14db.png" style="display: inline">

But I'm agree that this has some thing to do with #211 , because of the weird scaling behaviour it's easy to end up scale the avatar like this. This got fixed on pull request #268 by replacing the moveable library

**Comment by vickis** [comment]
It would be good to by default constrain proportions on scaling
perhaps though (if for example the avatar might want to grow tall and
skinny) then the frame should resize with the avatar

fyi on scaling if you use the corner handles _generally_ that constrains
proportions automatically
or holding down shift while you drag the handles

**Comment by helenvarley** [comment]
agree with vicki; corner handle scaling should constrain proportions, then the frame will always fit to the avatar. we don't want to crop or distort the avatar, we want it to scale with the same proportions.
will we see the fix of #211 / pull request #268  in R2-2021?

**Comment by nguyenhongphat0** [comment]
We already got #211 fixed. So what exactly is the action for this issue? Should I scale the avatar to fit the frame, like this:

![](https://user-images.githubusercontent.com/29925961/115186078-40defd80-a10b-11eb-8311-130d33ef14db.png)

**Comment by helenvarley** [comment]
no please not! the images should always have proportions constrained.
if #211 is fixed then that should address this too, but on R1-2021 at least, we can still get the problem of empty frame space above and below the image, which can mean that we can't access other media. but let's wait & see in R2 if this is still an issue.

**Comment by helenvarley** [comment]
ok i just looked now on https://dev-app1.upstage.org.nz/V4.0/ui/live/demo, and i can see that it is still an issue. having the frame extending above & below the avatar is going to cause problems because it takes up space on the stage where other media might be and will mean that we can accidentally select the wrong media item and sometimes not be able to select the one we want at all.  
the image should always retain its correct proportions, and the frame should always stay at the same proportions.

**Comment by nguyenhongphat0** [comment]
Okay from what I understand you want to "keep ratio". Let me know if the below behaviour match your expectation 😅 

https://user-images.githubusercontent.com/29925961/116196079-3b159780-a75d-11eb-99f5-8ea07307e6f8.mov

**Comment by helenvarley** [comment]
yes, perfect! :)

**Comment by vickis** [comment]
looks great :)
