### ISSUE TITLE
seeing different backdrop

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#339]
one of the players on stage was seeing a different backdrop: we were in the house and she was in the hospital:
![Screenshot at 2021-05-17 11-51-45](https://user-images.githubusercontent.com/3437324/118471210-c99b8a00-b707-11eb-8e2e-6414382e5708.png)

**Comment by helenvarley** [comment]
there is another screengrab coming of what mem was seeing at the same time

**Comment by millemem** [comment]
![Снимак екрана од 2021-05-17 11-52-18](https://user-images.githubusercontent.com/15329022/118476473-d6bb7780-b70d-11eb-8289-9e25933197b1.png)

**Comment by nguyenhongphat0** [comment]
I can't reproduce this issue, but technically this issue can be caused by 2 reasons:
- Package lost during transmission via `mqtt`. There's nothing I can do in this case. However we're using QoS level 2, which is the highest reliable level, package lost is very rare
- Racing condition: this happens when multiple backdrop changes are sent at the same time, and the backdrop that got received latest will took place. I solved this issue by send along the timestamp when the backdrop are changes, so that the backdrop should be the same to all players no matter which order they got received
Changes should be available on dev-app as soon as it got approved 👌

**Comment by helenvarley** [comment]
we have a LOT of experience with these kinds of discrepancy issues - & they are very difficult to replicate, especially on your own.
we are rehearsing again on monday, so we can test again. should we try on dev-app1 to see if it happens there?

**Comment by nguyenhongphat0** [comment]
Yes the fix not yet rolled into app1, so you must test on devapp

**Comment by helenvarley** [comment]
ok we will do on monday

**Comment by vickis** [comment]
multiple backdrops being sent makes sense with the new crew in and playing
about in the new space :)

**Comment by nguyenhongphat0** [comment]
Any update on this issues 🤔

**Comment by vickis** [comment]
We will be able to test this in our next artist meeting which is within 24
hours

**Comment by helenvarley** [comment]
sorry, we were going to drop in to the dev-app in order to test this morning during our rehearsal, but we got sidetracked by other issues - mostly the problem of being stuck behind things ... however, at least on app1 R2D2 this time we did not experience any backdrop discrepancies.

**Comment by nguyenhongphat0** [comment]
There is another cause of this issue, is the mongo queue sharing between app1 and devapp1, which is also the cause of #342. We already resolved #342, I'm sure this issue is gone as well 🙌
