### ISSUE TITLE
chat not recorded

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#342]
i just looked at the chat log for our Jeux de Massacre stage, where we rehearsed and tested for 2 hours this morning, and there are only 3 lines of chat there ... i have tried shift-refresh & still only 3 lines; there should be a lot more ...
https://app1.upstage.org.nz/V4.0/ui/backstage/stage-management/U3RhZ2U6MzU=/chat

**Comment by helenvarley** [comment]
whoops i didn't mean to add & remove those milestones on this issue :laughing:

**Comment by nguyenhongphat0** [comment]
This issue is resolved: chat is recorded correctly: https://app1.upstage.org.nz/V4.0/ui/backstage/stage-management/U3RhZ2U6MzU=/chat 🎉 

This was because I forgot to setup separated mongo queues for app and dev-app instances, which lead to these instance "stealing" each other events 🤐 An easier way to understand is some of your chat on app1 is recorded inside dev-app1 😅 This silly mistake bang my head to resolve.

**Comment by vickis** [comment]
Make sure you are getting rest also Phat :)

**Comment by helenvarley** [comment]
great! now we just need the time-separation ... :laughing:
