### ISSUE TITLE
separate buttons for clear chat and sweep stage

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#372]
currently there is one button in the stage management interface that is "clear chat and sweep stage"; this should be separated into two buttons, as you might sometimes want to clear the chat but not sweep the stage, or vice versa.

- "save and clear chat" - removes all text from the on-stage chat window, and saves it as a text file which is accessible from the chat tab in stage management
- "sweep stage" - clears all media from the stage

**Comment by vickis** [comment]
sounds good
useful to separate :)

**Comment by nguyenhongphat0** [comment]
Okay we now have 2 separated "Clear chat" and "Sweep stage" button
<img width="1036" alt="Screenshot 2021-06-27 at 20 59 20" src="https://user-images.githubusercontent.com/29925961/123547359-a940ff80-d78a-11eb-92cb-0f252d6c2ef5.png">

You can also clear the chat using the Setting tools, without having to leave the stage
<img width="577" alt="Screenshot 2021-06-27 at 21 00 54" src="https://user-images.githubusercontent.com/29925961/123547384-c675ce00-d78a-11eb-80dc-8cc836ff82e1.png">

Note: clear chat won't sweep the stage, but sweep the stage will clear all the chat. Because as I mentioned before, after sweeping the stage the archived events will be saved into a record. Chat must be part of the records, or else, you won't see our avatars speak anything when replaying it. Let me know if this sound okay to you, thank you 🙏

**Comment by helenvarley** [comment]
great!
