### ISSUE TITLE
streaming

### ISSUE THREAD

**Issue by vickis** [upstage-org/mobilise#4]
as an admin or any level down to player -  i want to able to add real time streaming to the stage the functionality of which is handled by an external source (eg WebRTC or other) this requires permission of the browser

**Comment by elisadcg** [comment]
And the stream appear like a backdrops ?

**Comment by helenvarley** [comment]
no - or at least, a stream backdrop would sometimes be useful. but the stream needs to appear on the stage as a manipulatable object.
sometimes there will be more than one stream, so we want to be able to adjust the stream size & move it around on the screen, & in front of or behind other objects.

**Comment by helenvarley** [comment]
this might be a useful read: https://www.derechosdigitales.org/wp-content/uploads/webrtc_en.pdf

**Comment by helenvarley** [comment]
tagging gloria & martin on this one - it's a high priority for R2! :sunglasses:

**Comment by helenvarley** [comment]
as an artist i want a stream tool that allows me to:
- display a live audio-visual stream from my webcam on the stage
- display a pre-recorded video from an online source on the stage
- send a live feed from my laptop, e.g. from a vjing or audio mixing software, to the stage
- select either audio, video, or audio and video to stream
- adjust the volume of the stream
- scale, rotate, move and fade in and out the stream (as done with avatars & props)

**Comment by nguyenhongphat0** [comment]
I believe this issue is resolved since we got the basic streaming checklist:
- [x] display a live audio-visual stream from my webcam on the stage
- [x] display a pre-recorded video from an online source on the stage **(you can do this by upload a mp4 file, or you can use OBS studio and set YouTube, webpage,... as stream source)**
- [x] send a live feed from my laptop, e.g. from a vjing or audio mixing software, to the stage
- [x] select either audio, video, or audio and video to stream
- [x] adjust the volume of the stream **(but this should be done in your stream source config)**
- [x] scale, rotate, move and fade in and out the stream (as done with avatars & props)

Further issue with streaming will have it own issue 🙌

**Comment by helenvarley** [comment]
just one thing - is it possible to have a volume control attached to a stream? it can be that the person sending the stream isn't also close to their computer, maybe not even hearing what is coming through on the stage, so they may not be able to adjust volume. it can also be that there is feedback and it's helpful if someone else on the stage can quickly mute or turn down a stream.

**Comment by vickis** [comment]
Agree volume control on stage is important
Even if it is just to mute & unmute (but changing  volume would be useful
too :)
This would be a useful addition to resize and transparency sliders
Thanks! :)
