### ISSUE TITLE
top navigation - doesn't work with certain screen resolutions

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/mobilise#541]
Manel found that there is a screen resolution issue: 
When the resolution is: 1200 x 1600 I can't hover nor click on: Stages - Media - Profile, but when I change the window to a screen resolution of 1920 x 1080 it works perfectly.
He's on Windows and tried Brave (Chrome) and Firefox.

On Linux using Chromium, I discovered that when i make the browser window smaller (which i often do), the top navigation menu is not clickable & the Stages menu item drops down a bit.
![Screenshot at 2021-08-31 12-45-46](https://user-images.githubusercontent.com/3437324/131423721-a4b35c77-7cc0-40ab-99c1-83695937b239.png)

**Comment by vickis** [comment]
I have the same issue :)

**Comment by vickis** [comment]
altering the screen resolution does not change it for me
mac/chrome or safari :(

**Comment by nguyenhongphat0** [comment]
Hi Vicki, I patched a hot fix on app1. Let me know if you still facing this issue 🙏

**Comment by helenvarley** [comment]
tested on firefox and chromium on linux: when i make the browser window narrow the top navigation buttons still work :) (until i make it even narrower and they disappear)

**Comment by vickis** [comment]
Yes working for me :)

**Comment by nguyenhongphat0** [comment]
> until i make it even narrower and they disappear

It was because you've reached tablet/phone breakpoint, so that the desktop navigation will disappear and you have to use that "hamburger navigation" instead.

<img width="974" alt="Screenshot 2021-09-03 at 14 47 15" src="https://user-images.githubusercontent.com/29925961/131969796-9a8f9aad-2ecf-45db-bb01-2b3f87675e51.png">

**Comment by nguyenhongphat0** [comment]
The mobile breakpoint is usually narrower, but in UpStage I have to made it wider because the menu items on the foyer is quite long, here is a screenshot. That's why you reach the breakpoint that soon 😅 

<img width="1034" alt="Screenshot 2021-09-03 at 14 47 53" src="https://user-images.githubusercontent.com/29925961/131970158-c6847d0e-03e7-4a7e-8e3a-997a3d9a7caa.png">

**Comment by helenvarley** [comment]
yes - that's totally fine :) the main thing is that when the buttons are there, they are clickable :)
